USE `tienda`;
SELECT nombre FROM `producto`;
SELECT nombre, precio FROM `producto`;
SELECT * FROM `producto`;
SELECT nombre, precio, precio * 1.08, 2 FROM `producto`;
SELECT nombre AS 'Nom de producto', precio AS 'euros', TRUNCATE(precio * 1.08, 2) AS 'dòlars' FROM `producto`;
SELECT UPPER(nombre), precio FROM `producto`;
SELECT LOWER(nombre), precio FROM `producto`;
SELECT nombre, UPPER(SUBSTRING(nombre,1,2)) FROM `fabricante`;
SELECT nombre, ROUND(precio,0) FROM `producto`;
SELECT nombre, TRUNCATE(precio,0) FROM `producto`;
SELECT fabricante.codigo FROM `producto` JOIN `fabricante` ON producto.codigo_fabricante = fabricante.codigo;
SELECT DISTINCT fabricante.codigo FROM `producto` JOIN `fabricante` ON producto.codigo_fabricante = fabricante.codigo;
SELECT nombre FROM `fabricante` ORDER BY nombre ASC;
SELECT nombre FROM `fabricante` ORDER BY nombre DESC;
SELECT nombre FROM `producto` ORDER BY nombre ASC, precio DESC;
SELECT * FROM `fabricante` LIMIT 5;
SELECT * FROM `fabricante` LIMIT 3,2;
SELECT nombre, precio FROM `producto` ORDER BY precio ASC LIMIT 1;
SELECT nombre, precio FROM `producto` ORDER BY precio DESC LIMIT 1;
SELECT producto.nombre FROM `producto` JOIN `fabricante` ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.codigo = 2;
SELECT producto.nombre, producto.precio, fabricante.nombre FROM `producto` JOIN `fabricante` ON producto.codigo_fabricante = fabricante.codigo;
SELECT producto.nombre, producto.precio, fabricante.nombre FROM `producto` JOIN `fabricante` ON producto.codigo_fabricante = fabricante.codigo ORDER BY fabricante.nombre ASC;
SELECT producto.codigo, producto.nombre, fabricante.codigo, fabricante.nombre FROM `producto` JOIN `fabricante` ON producto.codigo_fabricante = fabricante.codigo;
SELECT producto.nombre, producto.precio, fabricante.nombre FROM `producto` JOIN `fabricante` ON producto.codigo_fabricante = fabricante.codigo ORDER BY precio ASC LIMIT 1;
SELECT producto.nombre, producto.precio, fabricante.nombre FROM `producto` JOIN `fabricante` ON producto.codigo_fabricante = fabricante.codigo ORDER BY precio DESC LIMIT 1;
SELECT * FROM `producto` JOIN `fabricante` ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Lenovo';
SELECT * FROM `producto` JOIN `fabricante` ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Crucial' AND producto.precio > 200;
SELECT * FROM `producto` JOIN `fabricante` ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Asus' OR fabricante.nombre = 'Hewlett-Packard' OR fabricante.nombre = 'Seagate';
SELECT * FROM `producto` JOIN `fabricante` ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre IN ('Asus', 'Hewlett-Packard','Seagate');
SELECT producto.nombre, producto.precio FROM `producto` JOIN `fabricante` ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre LIKE '%e';
SELECT producto.nombre, producto.precio FROM `producto` JOIN `fabricante` ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre LIKE '%w%';
SELECT producto.nombre, producto.precio, fabricante.nombre FROM `producto` JOIN `fabricante` ON producto.codigo_fabricante = fabricante.codigo WHERE producto.precio >= 180 ORDER BY producto.precio DESC, producto.nombre ASC;
SELECT fabricante.codigo, fabricante.nombre FROM `producto` JOIN `fabricante` ON producto.codigo_fabricante = fabricante.codigo;
SELECT fabricante.nombre, producto.nombre FROM `producto` RIGHT JOIN `fabricante` ON producto.codigo_fabricante = fabricante.codigo;
SELECT fabricante.nombre FROM `producto` RIGHT JOIN `fabricante` ON producto.codigo_fabricante = fabricante.codigo WHERE producto.nombre IS NULL;
SELECT producto.nombre FROM `producto` LEFT JOIN `fabricante` ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Lenovo';
SELECT * FROM `producto` LEFT JOIN `fabricante` ON producto.codigo_fabricante = fabricante.codigo WHERE producto.precio = 559;
SELECT producto.nombre FROM `producto` JOIN `fabricante` ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Lenovo' ORDER BY producto.precio DESC LIMIT 1;
SELECT producto.nombre FROM `producto` JOIN `fabricante` ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Hewlett-Packard' ORDER BY producto.precio ASC LIMIT 1;
SELECT producto.nombre FROM `producto` LEFT JOIN `fabricante` ON producto.codigo_fabricante = fabricante.codigo WHERE producto.precio >= 559;
